# Generated by Django 2.2 on 2019-04-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_module_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Main_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Category')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Exams')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Levels')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Modules')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Module_Type')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Sub_modules')),
            ],
        ),
    ]
