# Generated by Django 2.2 on 2019-04-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetodemo', '0002_auto_20190419_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Levels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levels',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module_type',
            name='sub_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Sub_modules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Exams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_modules',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vetodemo.Modules'),
            preserve_default=False,
        ),
    ]
